import 'package:flutter/material.dart';

import './models/category.dart';
import './models/meal.dart';

const DUMMY_CATEGORIES = [
  Category(
    id: 'c1',
    title: 'Asian',
    color: Color(0xFFD52801),
  ),
  Category(
    id: 'c2',
    title: 'Breakfast',
    color: Color(0xFFFF6B0F),
  ),
  Category(
    id: 'c3',
    title: 'Beverages',
    color: Colors.amber,
  ),
  Category(
    id: 'c4',
    title: 'Dessert',
    color: Color(0xFFA8D161),
  ),
  Category(
    id: 'c5',
    title: 'Exotic',
    color: Color(0xFFD52801),
  ),
  Category(
    id: 'c6',
    title: 'Filipino',
    color: Color(0xFFFF6B0F),
  ),
  Category(
    id: 'c7',
    title: 'Italian',
    color: Colors.amber,
  ),
  Category(
    id: 'c8',
    title: 'Light & Lovely',
    color: Color(0xFFA8D161),
  ),
  Category(
    id: 'c9',
    title: 'Quick & Easy',
    color: Color(0xFFD52801),
  ),
  Category(
    id: 'c10',
    title: 'Summer',
    color: Color(0xFFFF6B0F),
  ),
];

const DUMMY_MEALS = [
  Meal(
    id: 'm1',
    categories: ['c1'],
    title: 'Korean BBQ Beef',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://www.allrecipes.com/thmb/G_UXncCchkMVeELX8DQMEwJOdHI=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/246172-Easy-Bulgogi-ddmfs-104-4x3-1-c0ddcab340474175a5d1c96bc2edabbc.jpg',
    duration: 30,
    ingredients: [
      'Beef (sliced thinly)',
      'Soy sauce',
      'Brown sugar',
      'Sesame oil',
      'Garlic',
      'Ginger',
      'Green onions',
      'Sesame seeds',
    ],
    steps: [
      'Marinate beef in soy sauce, brown sugar, sesame oil, garlic, and ginger.',
      'Grill or pan-fry beef until cooked.',
      'Garnish with green onions and sesame seeds.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm2',
    categories: ['c1'],
    title: 'Vietnamese Spring Rolls',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://www.cooking-therapy.com/wp-content/uploads/2022/05/Vietnamese-Spring-Rolls-Goi-Cuon-2.jpg',
    duration: 20,
    ingredients: [
      'Rice paper',
      'Shrimp or tofu',
      'Rice noodles',
      'Lettuce',
      'Mint',
      'Cilantro',
      'Peanut sauce',
    ],
    steps: [
      'Soak rice paper in water until pliable.',
      'Place lettuce, rice noodles, shrimp or tofu, mint, and cilantro on rice paper.',
      'Roll tightly and serve with peanut sauce.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm3',
    categories: ['c1'],
    title: 'Chinese Dumplings',
    affordability: Affordability.Affordable,
    complexity: Complexity.Challenging,
    imageUrl:
        'https://mamalovestocook.com/wp-content/uploads/2020/05/boiled-dumplings.jpg',
    duration: 60,
    ingredients: [
      'Dumpling wrappers',
      'Ground pork or chicken',
      'Cabbage',
      'Ginger',
      'Garlic',
      'Soy sauce',
      'Green onions',
      'Sesame oil',
    ],
    steps: [
      'Mix ground meat with finely chopped cabbage, ginger, garlic, soy sauce, green onions, and sesame oil.',
      'Place a spoonful of filling on each dumpling wrapper and seal.',
      'Steam or pan-fry until cooked.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm4',
    categories: ['c2'],
    title: 'Breakfast Burrito',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://kristineskitchenblog.com/wp-content/uploads/2023/02/breakfast-burrito-recipe-16.jpg',
    duration: 15,
    ingredients: [
      'Flour tortillas',
      'Eggs',
      'Cheese',
      'Cooked bacon or sausage',
      'Salsa',
    ],
    steps: [
      'Scramble eggs and cook until set.',
      'Warm tortillas in a pan.',
      'Fill tortillas with eggs, cheese, bacon or sausage.',
      'Roll up and serve with salsa.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm5',
    categories: ['c2', 'c9'],
    title: 'Oatmeal with Fresh Fruit',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://nenaswellnesscorner.com/wp-content/uploads/2023/07/Oatmeal-with-fruit-n1.jpg',
    duration: 10,
    ingredients: [
      'Oats',
      'Milk (or water)',
      'Fresh fruit (e.g., berries, banana)',
      'Honey or maple syrup',
    ],
    steps: [
      'Cook oats with milk or water according to package instructions.',
      'Top with fresh fruit and a drizzle of honey or syrup.',
    ],
    isGlutenFree: false, // unless using gluten-free oats
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm6',
    categories: ['c2'],
    title: 'Veggie Omelette',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://brooklynfarmgirl.com/wp-content/uploads/2016/02/Cheesy-Vegetable-Omelette_10-683x1024.jpg',
    duration: 15,
    ingredients: [
      'Eggs',
      'Bell peppers',
      'Spinach',
      'Onions',
      'Cheese (optional)',
      'Salt',
      'Pepper',
    ],
    steps: [
      'Beat eggs and season with salt and pepper.',
      'Sauté vegetables in a pan.',
      'Pour eggs over vegetables and cook until set.',
      'Fold omelette and serve.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm7',
    categories: ['c3'],
    title: 'Mango Smoothie',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://getinspiredeveryday.com/wp-content/uploads/2023/03/Mango-Smoothie-Get-Inspired-Everyday-8.jpg',
    duration: 10,
    ingredients: [
      'Mangoes',
      'Yogurt',
      'Honey',
      'Ice cubes',
    ],
    steps: [
      'Peel and chop mangoes.',
      'Blend mangoes, yogurt, honey, and ice until smooth.',
      'Pour into a glass and serve cold.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm8',
    categories: ['c3'],
    title: 'Iced Coffee',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://www.allrecipes.com/thmb/Hqro0FNdnDEwDjrEoxhMfKdWfOY=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/21667-easy-iced-coffee-ddmfs-4x3-0093-7becf3932bd64ed7b594d46c02d0889f.jpg',
    duration: 5,
    ingredients: [
      'Coffee',
      'Ice cubes',
      'Milk',
      'Sugar',
    ],
    steps: [
      'Brew coffee and let it cool.',
      'Fill a glass with ice cubes.',
      'Pour coffee over ice.',
      'Add milk and sugar to taste.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm9',
    categories: ['c3'],
    title: 'Lemonade',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://www.jocooks.com/wp-content/uploads/2023/05/lemonade-1-28.jpg',
    duration: 10,
    ingredients: [
      'Lemons',
      'Sugar',
      'Water',
      'Ice cubes',
    ],
    steps: [
      'Squeeze lemons to get juice.',
      'Mix lemon juice with water and sugar.',
      'Stir until sugar dissolves.',
      'Add ice cubes and serve cold.',
    ],
    isGlutenFree: true,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm10',
    categories: ['c4'],
    title: 'Chocolate Lava Cake',
    affordability: Affordability.Pricey,
    complexity: Complexity.Challenging,
    imageUrl:
        'https://www.rachelcooks.com/wp-content/uploads/2023/01/Chocolate-Lava-Cakes019-web-square.jpg',
    duration: 30,
    ingredients: [
      'Dark chocolate',
      'Butter',
      'Eggs',
      'Sugar',
      'Flour',
      'Vanilla extract',
    ],
    steps: [
      'Melt chocolate and butter together.',
      'Mix in eggs, sugar, and vanilla.',
      'Stir in flour and pour into greased ramekins.',
      'Bake until edges are set but centers are still gooey.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm11',
    categories: ['c4'],
    title: 'Lemon Sorbet',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://www.mybakingaddiction.com/wp-content/uploads/2009/06/close-up-lemon-sorbet-hero.jpg',
    duration: 120,
    ingredients: [
      'Lemon juice',
      'Sugar',
      'Water',
    ],
    steps: [
      'Dissolve sugar in water to make a simple syrup.',
      'Mix in lemon juice.',
      'Freeze mixture, stirring occasionally until firm.',
    ],
    isGlutenFree: true,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm12',
    categories: ['c4'],
    title: 'Tiramisu',
    affordability: Affordability.Pricey,
    complexity: Complexity.Challenging,
    imageUrl:
        'https://www.culinaryhill.com/wp-content/uploads/2021/01/Tiramisu-Culinary-Hill-1200x800-1.jpg',
    duration: 240,
    ingredients: [
      'Ladyfingers',
      'Mascarpone cheese',
      'Coffee',
      'Eggs',
      'Sugar',
      'Cocoa powder',
    ],
    steps: [
      'Dip ladyfingers in coffee and layer in a dish.',
      'Mix mascarpone cheese with egg yolks and sugar.',
      'Spread cheese mixture over ladyfingers.',
      'Refrigerate for several hours and dust with cocoa powder before serving.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm13',
    categories: ['c5'],
    title: 'Sushi Rolls',
    affordability: Affordability.Pricey,
    complexity: Complexity.Challenging,
    imageUrl: 'https://i.ndtvimg.com/i/2018-02/rolls_620x330_41518089610.jpg',
    duration: 60,
    ingredients: [
      'Sushi rice',
      'Nori (seaweed)',
      'Fresh fish (e.g., tuna or salmon)',
      'Avocado',
      'Cucumber',
      'Soy sauce',
      'Wasabi',
    ],
    steps: [
      'Cook and season sushi rice.',
      'Lay a sheet of nori on a bamboo mat.',
      'Spread rice over nori, leaving a border.',
      'Add fish, avocado, and cucumber.',
      'Roll tightly and slice into pieces.',
      'Serve with soy sauce and wasabi.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm14',
    categories: ['c5'],
    title: 'Japanese Ramen',
    affordability: Affordability.Pricey,
    complexity: Complexity.Challenging,
    imageUrl:
        'https://media1.sacurrent.com/sacurrent/imager/28-essential-ramen-and-pho-spots-in-san-antonio-to-get-your-noodle-fix/u/zoom/27145779/kimura.png?cb=1642780090',
    duration: 60,
    ingredients: [
      'Ramen noodles',
      'Pork belly',
      'Soy sauce',
      'Miso paste',
      'Garlic',
      'Ginger',
      'Green onions',
      'Eggs',
      'Nori',
    ],
    steps: [
      'Cook pork belly and set aside.',
      'Prepare broth with soy sauce, miso paste, garlic, and ginger.',
      'Cook ramen noodles in the broth.',
      'Top with sliced pork belly, green onions, and a soft-boiled egg.',
      'Garnish with nori.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm15',
    categories: ['c5'],
    title: 'Korean Bibimbap',
    affordability: Affordability.Affordable,
    complexity: Complexity.Challenging,
    imageUrl:
        'https://feastandflight.com/wp-content/uploads/2020/01/IMG_8288-ltr-scaled.jpg',
    duration: 45,
    ingredients: [
      'Rice',
      'Beef (or tofu)',
      'Spinach',
      'Carrots',
      'Bean sprouts',
      'Egg',
      'Gochujang (Korean chili paste)',
      'Soy sauce',
    ],
    steps: [
      'Cook rice and set aside.',
      'Sauté beef and vegetables separately.',
      'Mix gochujang with soy sauce for a sauce.',
      'Assemble rice, beef, vegetables, and a fried egg in a bowl.',
      'Top with sauce and serve.',
    ],
    isGlutenFree: false, // if gochujang contains gluten
    isVegan: false,
    isVegetarian: false, // unless using tofu
    isLactoseFree: true,
  ),
  Meal(
    id: 'm16',
    categories: ['c6'],
    title: 'Lumpia',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://www.allrecipes.com/thmb/91kDp_3WYGHzsmMkXnDP5s9mBGI=/0x512/filters:no_upscale():max_bytes(150000):strip_icc()/35151-traditional-filipino-lumpia-ddmfs-hero-1x2-0745-d25195def74049598ca7cfa057f9d77e.jpg',
    duration: 60,
    ingredients: [
      'Ground pork',
      'Carrots',
      'Green beans',
      'Garlic',
      'Onions',
      'Soy sauce',
      'Spring roll wrappers',
      'Oil for frying',
    ],
    steps: [
      'Sauté garlic and onions.',
      'Add ground pork and cook until browned.',
      'Add carrots and green beans, cook until tender.',
      'Season with soy sauce.',
      'Wrap the filling in spring roll wrappers.',
      'Fry until golden brown.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm17',
    categories: ['c6'],
    title: 'Pancit',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://i0.wp.com/plantbased-passport.com/wp-content/uploads/vegan-filipino-pancit-bihon-10.jpg?resize=720%2C900&ssl=1',
    duration: 30,
    ingredients: [
      'Rice noodles',
      'Chicken',
      'Vegetables',
      'Soy sauce',
    ],
    steps: [
      'Cook chicken and vegetables.',
      'Add noodles.',
      'Add soy sauce and stir-fry.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm18',
    categories: ['c6', 'c4', 'c10'],
    title: 'Halo-Halo',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://assets.bonappetit.com/photos/60e46c6701084801b06de2a3/1:1/w_2560%2Cc_limit/Halo-Halo-Recipe-2021.jpg',
    duration: 15,
    ingredients: [
      'Crushed ice',
      'Sweet beans',
      'Jellies',
      'Fruits',
      'Leche flan',
      'Ube ice cream',
    ],
    steps: [
      'Layer ingredients in a glass.',
      'Top with ice cream.',
      'Serve cold.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm19',
    categories: ['c7'],
    title: 'Margherita Pizza',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://images.prismic.io/eataly-us/ed3fcec7-7994-426d-a5e4-a24be5a95afd_pizza-recipe-main.jpg',
    duration: 30,
    ingredients: [
      'Pizza dough',
      'Tomato sauce',
      'Mozzarella',
      'Basil',
      'Olive oil',
    ],
    steps: [
      'Prepare dough.',
      'Spread sauce.',
      'Add cheese and basil.',
      'Bake.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm20',
    categories: ['c7'],
    title: 'Spaghetti Carbonara',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Espaguetis_carbonara.jpg/800px-Espaguetis_carbonara.jpg',
    duration: 20,
    ingredients: [
      'Spaghetti',
      'Eggs',
      'Pecorino Romano',
      'Guanciale',
      'Black Pepper',
    ],
    steps: [
      'Cook spaghetti.',
      'Fry guanciale.',
      'Mix eggs and cheese.',
      'Combine everything.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm21',
    categories: ['c7'],
    title: 'Chicken Parmesan',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://www.homemadeitaliancooking.com/wp-content/uploads/2015/06/Chicken-Parmesan-in-pan.jpg',
    duration: 40,
    ingredients: [
      '6 boneless skinless chicken breast',
      'flour',
      'eggs',
      'cream',
      'Salt & black pepper',
      'minced flat leaf parsley',
      'breadcrumbs',
      'parmesan cheese',
      'olive oil',
      'Marinara Sauce',
      'milk mozzarella',
    ],
    steps: [
      'Bread the chicken with flour, egg, and breadcrumbs mixed with Parmesan.',
      'Fry the breaded chicken until golden brown.',
      'Top with marinara sauce and mozzarella.',
      'Bake until cheese is melted and bubbly.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm22',
    categories: ['c8'],
    title: 'Cucumber and Hummus Sandwiches',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://www.eatingwell.com/thmb/0gjj7z0ii3PXmAcb7ubZK2RZbTI=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/cucumber-sandwich-7949991-3x2-f111dce9bcf44c788803c46a0c31f330.jpg',
    duration: 10,
    ingredients: [
      'Whole grain bread',
      'Hummus',
      'Cucumber slices',
      'Salt',
      'Pepper',
    ],
    steps: [
      'Spread hummus on bread slices.',
      'Layer cucumber slices on top.',
      'Season with salt and pepper.',
      'Close sandwiches and cut into halves.',
    ],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm23',
    categories: ['c8'],
    title: 'Spinach and Strawberry Salad',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://www.allrecipes.com/thmb/7OjjcmRQC8Sb236VtRX5YljlaIQ=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/4535439-564adcef998c47bebfcb6d9c5aa2a3df.jpg',
    duration: 10,
    ingredients: [
      'Spinach',
      'Strawberries',
      'Feta cheese',
      'Walnuts',
      'Balsamic vinaigrette',
    ],
    steps: [
      'Toss spinach and sliced strawberries in a bowl.',
      'Add crumbled feta and walnuts.',
      'Drizzle with balsamic vinaigrette.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm24',
    categories: ['c8'],
    title: 'Tomato Basil Soup',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://therecipecritic.com/wp-content/uploads/2022/10/tomatobasilsoup-4-750x1000.jpg',
    duration: 30,
    ingredients: [
      'Tomatoes',
      'Onion',
      'Garlic',
      'Basil',
      'Olive oil',
      'Vegetable broth',
      'Salt',
      'Pepper',
    ],
    steps: [
      'Sauté onions and garlic in olive oil.',
      'Add tomatoes and vegetable broth, and bring to a simmer.',
      'Blend until smooth.',
      'Stir in basil and season with salt and pepper.',
    ],
    isGlutenFree: true,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm25',
    categories: ['c9'],
    title: 'Grilled Cheese Sandwich',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F9416780.jpg&q=60&c=sc&poi=auto&orient=true&h=512',
    duration: 10,
    ingredients: [
      'Cheddar cheese',
      'bread',
      'fresh parsley',
      'basil',
      'butter',
    ],
    steps: [
      'Butter bread.',
      'Add cheese.',
      'Grill until golden brown.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm26',
    categories: ['c9'],
    title: 'Caesar Salad',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://natashaskitchen.com/wp-content/uploads/2019/01/Caesar-Salad-Recipe-3.jpg',
    duration: 15,
    ingredients: [
      'Romaine lettuce',
      'Caesar dressing',
      'Croutons',
      'Parmesan cheese',
      'Mayonnaise',
    ],
    steps: [
      'Chop lettuce.',
      'Add dressing.',
      'Sprinkle croutons and cheese.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm27',
    categories: ['c9'],
    title: 'Stir-Fried Vegetables',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://natashaskitchen.com/wp-content/uploads/2020/08/Vegetable-Stir-Fry-2.jpg',
    duration: 15,
    ingredients: [
      'Mixed vegetables',
      'Soy sauce',
      'Garlic',
      'Olive oil',
    ],
    steps: [
      'Heat oil.',
      'Add garlic.',
      'Stir-fry vegetables.',
      'Add soy sauce.',
    ],
    isGlutenFree: true,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm28',
    categories: ['c10', 'c9'],
    title: 'Yogurt Parfait',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://feelgoodfoodie.net/wp-content/uploads/2021/05/fruit-and-yogurt-parfait-09.jpg',
    duration: 10,
    ingredients: [
      'Greek yogurt',
      'Granola',
      'Mixed berries',
      'Honey',
    ],
    steps: [
      'Layer yogurt, granola, mixed berries in a glass.',
      'Drizzle with honey.',
      'Repeat layers as desired.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm29',
    categories: ['c10'],
    title: 'Watermelon Feta Salad',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://www.seriouseats.com/thmb/4q2pHbYsYhMXVHEdISs3u7IMTTo=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/20210524-Watermelon-Feta-Mint-Salad-liz-voltz-seriouseats-4-cce131458da64fd2a5e64a4bf77def90.jpg',
    duration: 15,
    ingredients: [
      'Watermelon',
      'Feta cheese',
      'Mint leaves',
      'Olive oil',
      'Lime juice',
      'Salt',
      'Pepper',
    ],
    steps: [
      'Cut watermelon into cubes.',
      'Crumble feta cheese over watermelon.',
      'Add chopped mint leaves.',
      'Drizzle with olive oil and lime juice.',
      'Season with salt and pepper.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm30',
    categories: ['c10', 'c9'],
    title: 'Caprese Salad',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://i2.wp.com/www.downshiftology.com/wp-content/uploads/2019/07/Caprese-Salad-main-1.jpg',
    duration: 10,
    ingredients: [
      'Tomatoes',
      'Fresh mozzarella',
      'Basil',
      'Olive oil',
      'Balsamic glaze',
      'Salt',
      'Pepper',
    ],
    steps: [
      'Slice tomatoes and mozzarella.',
      'Arrange slices on a plate, alternating tomato and mozzarella.',
      'Top with basil leaves.',
      'Drizzle with olive oil and balsamic glaze.',
      'Season with salt and pepper.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
];
