import 'package:flutter/material.dart';

import './models/category.dart';
import './models/meal.dart';

const DUMMY_CATEGORIES = [
  Category(
    id: 'c1',
    title: 'Asian',
    color: Color(0xFFD52801),
  ),
  Category(
    id: 'c2',
    title: 'Breakfast',
    color: Color(0xFFFF6B0F),
  ),
  Category(
    id: 'c3',
    title: 'Beverages',
    color: Colors.amber,
  ),
  Category(
    id: 'c4',
    title: 'Dessert',
    color: Color(0xFFA8D161),
  ),
  Category(
    id: 'c5',
    title: 'Exotic',
    color: Color(0xFFD52801),
  ),
  Category(
    id: 'c6',
    title: 'Filipino',
    color: Color(0xFFFF6B0F),
  ),
  Category(
    id: 'c7',
    title: 'Italian',
    color: Colors.amber,
  ),
  Category(
    id: 'c8',
    title: 'Light & Lovely',
    color: Color(0xFFA8D161),
  ),
  Category(
    id: 'c9',
    title: 'Quick & Easy',
    color: Color(0xFFD52801),
  ),
  Category(
    id: 'c10',
    title: 'Summer',
    color: Color(0xFFFF6B0F),
  ),
];

const DUMMY_MEALS = [
  Meal(
    id: 'm10',
    categories: ['c3'],
    title: 'Mango Smoothie',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://getinspiredeveryday.com/wp-content/uploads/2023/03/Mango-Smoothie-Get-Inspired-Everyday-8.jpg',
    duration: 10,
    ingredients: [
      'Mangoes',
      'Yogurt',
      'Honey',
      'Ice cubes',
    ],
    steps: [
      'Peel and chop mangoes.',
      'Blend mangoes, yogurt, honey, and ice until smooth.',
      'Pour into a glass and serve cold.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm11',
    categories: ['c3'],
    title: 'Iced Coffee',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://www.allrecipes.com/thmb/Hqro0FNdnDEwDjrEoxhMfKdWfOY=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/21667-easy-iced-coffee-ddmfs-4x3-0093-7becf3932bd64ed7b594d46c02d0889f.jpg',
    duration: 5,
    ingredients: [
      'Coffee',
      'Ice cubes',
      'Milk',
      'Sugar',
    ],
    steps: [
      'Brew coffee and let it cool.',
      'Fill a glass with ice cubes.',
      'Pour coffee over ice.',
      'Add milk and sugar to taste.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm12',
    categories: ['c3'],
    title: 'Lemonade',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://www.jocooks.com/wp-content/uploads/2023/05/lemonade-1-28.jpg',
    duration: 10,
    ingredients: [
      'Lemons',
      'Sugar',
      'Water',
      'Ice cubes',
    ],
    steps: [
      'Squeeze lemons to get juice.',
      'Mix lemon juice with water and sugar.',
      'Stir until sugar dissolves.',
      'Add ice cubes and serve cold.',
    ],
    isGlutenFree: true,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm7',
    categories: ['c5'],
    title: 'Lumpia',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://www.allrecipes.com/thmb/91kDp_3WYGHzsmMkXnDP5s9mBGI=/0x512/filters:no_upscale():max_bytes(150000):strip_icc()/35151-traditional-filipino-lumpia-ddmfs-hero-1x2-0745-d25195def74049598ca7cfa057f9d77e.jpg',
    duration: 60,
    ingredients: [
      'Ground pork',
      'Carrots',
      'Green beans',
      'Garlic',
      'Onions',
      'Soy sauce',
      'Spring roll wrappers',
      'Oil for frying',
    ],
    steps: [
      'Sauté garlic and onions.',
      'Add ground pork and cook until browned.',
      'Add carrots and green beans, cook until tender.',
      'Season with soy sauce.',
      'Wrap the filling in spring roll wrappers.',
      'Fry until golden brown.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm8',
    categories: ['c5'],
    title: 'Pancit',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://i0.wp.com/plantbased-passport.com/wp-content/uploads/vegan-filipino-pancit-bihon-10.jpg?resize=720%2C900&ssl=1',
    duration: 30,
    ingredients: [
      'Rice noodles',
      'Chicken',
      'Vegetables',
      'Soy sauce',
    ],
    steps: [
      'Cook chicken and vegetables.',
      'Add noodles.',
      'Add soy sauce and stir-fry.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm9',
    categories: ['c5'],
    title: 'Halo-Halo',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://assets.bonappetit.com/photos/60e46c6701084801b06de2a3/1:1/w_2560%2Cc_limit/Halo-Halo-Recipe-2021.jpg',
    duration: 15,
    ingredients: [
      'Crushed ice',
      'Sweet beans',
      'Jellies',
      'Fruits',
      'Leche flan',
      'Ube ice cream',
    ],
    steps: [
      'Layer ingredients in a glass.',
      'Top with ice cream.',
      'Serve cold.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm3',
    categories: ['c7'],
    title: 'Margherita Pizza',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://images.prismic.io/eataly-us/ed3fcec7-7994-426d-a5e4-a24be5a95afd_pizza-recipe-main.jpg',
    duration: 30,
    ingredients: [
      'Pizza dough',
      'Tomato sauce',
      'Mozzarella',
      'Basil',
      'Olive oil',
    ],
    steps: [
      'Prepare dough.',
      'Spread sauce.',
      'Add cheese and basil.',
      'Bake.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm2',
    categories: ['c7'],
    title: 'Spaghetti Carbonara',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Espaguetis_carbonara.jpg/800px-Espaguetis_carbonara.jpg',
    duration: 20,
    ingredients: [
      'Spaghetti',
      'Eggs',
      'Pecorino Romano',
      'Guanciale',
      'Black Pepper',
    ],
    steps: [
      'Cook spaghetti.',
      'Fry guanciale.',
      'Mix eggs and cheese.',
      'Combine everything.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm1',
    categories: ['c7'],
    title: 'Chicken Parmesan',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://www.homemadeitaliancooking.com/wp-content/uploads/2015/06/Chicken-Parmesan-in-pan.jpg',
    duration: 40,
    ingredients: [
      '6 boneless skinless chicken breast',
      'flour',
      'eggs',
      'cream',
      'Salt & black pepper',
      'minced flat leaf parsley',
      'breadcrumbs',
      'parmesan cheese',
      'olive oil',
      'Marinara Sauce',
      'milk mozzarella',
    ],
    steps: [
      'Bread the chicken with flour, egg, and breadcrumbs mixed with Parmesan.',
      'Fry the breaded chicken until golden brown.',
      'Top with marinara sauce and mozzarella.',
      'Bake until cheese is melted and bubbly.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm4',
    categories: ['c9'],
    title: 'Grilled Cheese Sandwich',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F9416780.jpg&q=60&c=sc&poi=auto&orient=true&h=512',
    duration: 10,
    ingredients: [
      'Cheddar cheese',
      'bread',
      'fresh parsley',
      'basil',
      'butter',
    ],
    steps: [
      'Butter bread.',
      'Add cheese.',
      'Grill until golden brown.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm5',
    categories: ['c9'],
    title: 'Caesar Salad',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://natashaskitchen.com/wp-content/uploads/2019/01/Caesar-Salad-Recipe-3.jpg',
    duration: 15,
    ingredients: [
      'Romaine lettuce',
      'Caesar dressing',
      'Croutons',
      'Parmesan cheese',
      'Mayonnaise',
    ],
    steps: [
      'Chop lettuce.',
      'Add dressing.',
      'Sprinkle croutons and cheese.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm',
    categories: ['c9'],
    title: 'Stir-Fried Vegetables',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://natashaskitchen.com/wp-content/uploads/2020/08/Vegetable-Stir-Fry-2.jpg',
    duration: 15,
    ingredients: [
      'Mixed vegetables',
      'Soy sauce',
      'Garlic',
      'Olive oil',
    ],
    steps: [
      'Heat oil.',
      'Add garlic.',
      'Stir-fry vegetables.',
      'Add soy sauce.',
    ],
    isGlutenFree: true,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm13',
    categories: ['c10'],
    title: 'Yogurt Parfait',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://feelgoodfoodie.net/wp-content/uploads/2021/05/fruit-and-yogurt-parfait-09.jpg',
    duration: 10,
    ingredients: [
      'Greek yogurt',
      'Granola',
      'Mixed berries',
      'Honey',
    ],
    steps: [
      'Layer yogurt, granola, mixed berries in a glass.',
      'Drizzle with honey.',
      'Repeat layers as desired.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm14',
    categories: ['c10'],
    title: 'Watermelon Feta Salad',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://www.seriouseats.com/thmb/4q2pHbYsYhMXVHEdISs3u7IMTTo=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/20210524-Watermelon-Feta-Mint-Salad-liz-voltz-seriouseats-4-cce131458da64fd2a5e64a4bf77def90.jpg',
    duration: 15,
    ingredients: [
      'Watermelon',
      'Feta cheese',
      'Mint leaves',
      'Olive oil',
      'Lime juice',
      'Salt',
      'Pepper',
    ],
    steps: [
      'Cut watermelon into cubes.',
      'Crumble feta cheese over watermelon.',
      'Add chopped mint leaves.',
      'Drizzle with olive oil and lime juice.',
      'Season with salt and pepper.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm15',
    categories: ['c10'],
    title: 'Caprese Salad',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://i2.wp.com/www.downshiftology.com/wp-content/uploads/2019/07/Caprese-Salad-main-1.jpg',
    duration: 10,
    ingredients: [
      'Tomatoes',
      'Fresh mozzarella',
      'Basil',
      'Olive oil',
      'Balsamic glaze',
      'Salt',
      'Pepper',
    ],
    steps: [
      'Slice tomatoes and mozzarella.',
      'Arrange slices on a plate, alternating tomato and mozzarella.',
      'Top with basil leaves.',
      'Drizzle with olive oil and balsamic glaze.',
      'Season with salt and pepper.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
];
